version: '3.8'
services:
  frontend:
    container_name: angular-frontend-container
    build:
      context: ./my_project
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    environment:
      - BACKEND_URL=http://django-backend-container:8000
    depends_on:
      - backend
    networks:
      - my-network

  backend:
    container_name: django-backend-container
    build:
      context: ./sop_django
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./sop_django:/app
    ports:
      - "8000:8000"
    depends_on:
      - db  # Change from mysql to db
    environment:
      - DB_HOST=db  # Change from mysql to db
      - DB_NAME=sop_django
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_PORT=3306
    networks:
      - my-network      

  db:
    container_name: mysql-container  
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: sop_django
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge      

volumes:
  mysql_data:
